plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: "C:\\Users\\Utilisateur\\Documents\\dev\\uploaderExpress\\.yarn\\releases\\yarn-berry.js"
